---
  name: Packaging

  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

  env:
    CTEST_OUTPUT_ON_FAILURE: 1
    CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: "**/cpm_modules"
            key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

        - name: build for packaging
          run: |
            cmake -S test/packaging -B build/packaging
            cd build/packaging
            cpack -G DEB .
            dpkg -I *deb | grep "Maintainer: Foo Bar <foo@bar.local>"
