name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: 3.18.4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install format dependencies
        run: pip3 install clang-format==14.0.6 cmake_format==0.6.11 pyyaml

      - name: configure
        run: cmake -S test/style -B build/style

      - name: check style
        run: cmake --build build/style --target check-format
